In [36]:
# Imports

# Data Manipulation and Analysis
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

# Machine Learning preprocessing and splitting
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Machine Learning Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Evaluation metrics
from sklearn.metrics import accuracy_score, recall_score, f1_score, classification_report,roc_auc_score, confusion_matrix

# To save our model later
import joblib

# Supress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

In [26]:
# Data Loading

df = pd.read_excel('Prediction_Data.xlsx', sheet_name = 'Sheet1')
display(df.head())
print(f"Dataset shape: {df.shape[0]} rows and {df.shape[1]} columns")


,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Churn_Category,Churn_Reason
0,19877-DEL,Male,35,No,Delhi,7,27,NaN,Yes,No,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,Not Applicable,Not Applicabe
1,58353-MAH,Female,45,Yes,Maharashtra,14,13,NaN,Yes,Yes,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,Not Applicable,Not Applicabe
2,25063-WES,Male,51,No,West Bengal,4,35,Deal 5,Yes,No,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,59787-KAR,Male,79,No,Karnataka,3,21,Deal 4,Yes,No,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,28544-TAM,Female,80,No,Tamil Nadu,3,8,NaN,Yes,No,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability


Dataset shape: 6007 rows and 32 columns


In [27]:
# Columns 
df.columns

Index(['Customer_ID', 'Gender', 'Age', 'Married', 'State',
       'Number_of_Referrals', 'Tenure_in_Months', 'Value_Deal',
       'Phone_Service', 'Multiple_Lines', 'Internet_Service', 'Internet_Type',
       'Online_Security', 'Online_Backup', 'Device_Protection_Plan',
       'Premium_Support', 'Streaming_TV', 'Streaming_Movies',
       'Streaming_Music', 'Unlimited_Data', 'Contract', 'Paperless_Billing',
       'Payment_Method', 'Monthly_Charge', 'Total_Charges', 'Total_Refunds',
       'Total_Extra_Data_Charges', 'Total_Long_Distance_Charges',
       'Total_Revenue', 'Customer_Status', 'Churn_Category', 'Churn_Reason'],
      dtype='object')

In [28]:
# Droping columns that cause data leakage or have no predictive power
columns_to_drop = ['Customer_ID','Churn_Category','Churn_Reason']
df = df.drop(columns=columns_to_drop)
df.columns

Index(['Gender', 'Age', 'Married', 'State', 'Number_of_Referrals',
       'Tenure_in_Months', 'Value_Deal', 'Phone_Service', 'Multiple_Lines',
       'Internet_Service', 'Internet_Type', 'Online_Security', 'Online_Backup',
       'Device_Protection_Plan', 'Premium_Support', 'Streaming_TV',
       'Streaming_Movies', 'Streaming_Music', 'Unlimited_Data', 'Contract',
       'Paperless_Billing', 'Payment_Method', 'Monthly_Charge',
       'Total_Charges', 'Total_Refunds', 'Total_Extra_Data_Charges',
       'Total_Long_Distance_Charges', 'Total_Revenue', 'Customer_Status'],
      dtype='object')

In [29]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Gender                       6007 non-null   object 
 1   Age                          6007 non-null   int64  
 2   Married                      6007 non-null   object 
 3   State                        6007 non-null   object 
 4   Number_of_Referrals          6007 non-null   int64  
 5   Tenure_in_Months             6007 non-null   int64  
 6   Value_Deal                   2710 non-null   object 
 7   Phone_Service                6007 non-null   object 
 8   Multiple_Lines               6007 non-null   object 
 9   Internet_Service             6007 non-null   object 
 10  Internet_Type                4784 non-null   object 
 11  Online_Security              6007 non-null   object 
 12  Online_Backup                6007 non-null   object 
 13  Device_Protection_

In [30]:
# Missing Values

df.isnull().sum()

Gender                            0
Age                               0
Married                           0
State                             0
Number_of_Referrals               0
Tenure_in_Months                  0
Value_Deal                     3297
Phone_Service                     0
Multiple_Lines                    0
Internet_Service                  0
Internet_Type                  1223
Online_Security                   0
Online_Backup                     0
Device_Protection_Plan            0
Premium_Support                   0
Streaming_TV                      0
Streaming_Movies                  0
Streaming_Music                   0
Unlimited_Data                    0
Contract                          0
Paperless_Billing                 0
Payment_Method                    0
Monthly_Charge                    0
Total_Charges                     0
Total_Refunds                     0
Total_Extra_Data_Charges          0
Total_Long_Distance_Charges       0
Total_Revenue               

In [31]:
# Handle Missing Values

df['Value_Deal'].fillna('None',inplace=True)
df['Internet_Type'].fillna(df['Internet_Type'].mode()[0],inplace=True)
df.isnull().sum()

Gender                         0
Age                            0
Married                        0
State                          0
Number_of_Referrals            0
Tenure_in_Months               0
Value_Deal                     0
Phone_Service                  0
Multiple_Lines                 0
Internet_Service               0
Internet_Type                  0
Online_Security                0
Online_Backup                  0
Device_Protection_Plan         0
Premium_Support                0
Streaming_TV                   0
Streaming_Movies               0
Streaming_Music                0
Unlimited_Data                 0
Contract                       0
Paperless_Billing              0
Payment_Method                 0
Monthly_Charge                 0
Total_Charges                  0
Total_Refunds                  0
Total_Extra_Data_Charges       0
Total_Long_Distance_Charges    0
Total_Revenue                  0
Customer_Status                0
dtype: int64

In [32]:
# Encode te Target Variable

df['Customer_Status'] = df['Customer_Status'].map({'Churned':1, 'Stayed':0})

print(df['Customer_Status'].value_counts())


Customer_Status
0    4275
1    1732
Name: count, dtype: int64


In [33]:
# Featuer Engineering (One-Hot Encoding)

X = df.drop('Customer_Status', axis=1)
y = df['Customer_Status']

# Categorical columns into numeric binary columns
X_encoded = pd.get_dummies(X, drop_first=True)

# Save the final column names for later use
training_columns = X_encoded.columns
joblib.dump(training_columns, 'training_columns.joblib')

print(f"Categorical features encoded.We now have {X_encoded.shape[1]} features.")

Categorical features encoded.We now have 55 features.


In [35]:
# Train/Test Split & Feature Scaling

X_train,X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


joblib.dump(scaler, 'scaler.joblib')




['scaler.joblib']

In [40]:
# Setup Evaluation Function & Extra Metrics
model_performance = {}

def evaluate_and_store(model_name, model, X_test, y_test):
    y_pred = model.predict(X_test)

    y_pred_proba = model.predict_proba(X_test)[:,1]

    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test,y_pred)
    auc_roc = roc_auc_score(y_test, y_pred_proba)

    print(f"=========== {model_name} ===========")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,y_pred))
    print("\nClassification Report: ")
    print(classification_report(y_test,y_pred))
    print(f"AUC-ROC Score: {auc_roc:.4f}")
    print("============================================\n")

    model_performance[model_name] = {
        'Accuracy' : accuracy,
        'Recall' : recall,
        'F1-Score' : f1,
        'AUC-ROC' : auc_roc
    }

In [41]:
# Logistic Regression

log_reg_simple = LogisticRegression(penalty=None, class_weight='balanced',random_state=42)

log_reg_simple.fit(X_train_scaled, y_train)

evaluate_and_store("Logistic Regression",log_reg_simple, X_test_scaled, y_test)

=========== Logistic Regression ===========
Confusion Matrix:
[[658 197]
 [ 66 281]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.91      0.77      0.83       855
           1       0.59      0.81      0.68       347

    accuracy                           0.78      1202
   macro avg       0.75      0.79      0.76      1202
weighted avg       0.82      0.78      0.79      1202

AUC-ROC Score: 0.8708



In [42]:
# Logistic Regression (L1/Lasso)

log_reg_l1 = LogisticRegression(penalty='l1',solver='liblinear', class_weight='balanced',random_state=42)
log_reg_l1.fit(X_train_scaled, y_train)

evaluate_and_store("Logistic Regression (L1/Lasso)",log_reg_l1,X_test_scaled,y_test)

=========== Logistic Regression (L1/Lasso) ===========
Confusion Matrix:
[[658 197]
 [ 66 281]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.91      0.77      0.83       855
           1       0.59      0.81      0.68       347

    accuracy                           0.78      1202
   macro avg       0.75      0.79      0.76      1202
weighted avg       0.82      0.78      0.79      1202

AUC-ROC Score: 0.8709



In [43]:
# Logistic Regression (L2/Ridge)

log_reg_l2 = LogisticRegression(penalty='l2', class_weight='balanced',random_state=42)
log_reg_l2.fit(X_train_scaled, y_train)

evaluate_and_store("Logistic Regression (L2/Ridge)",log_reg_l2,X_test_scaled,y_test)

=========== Logistic Regression (L2/Ridge) ===========
Confusion Matrix:
[[658 197]
 [ 66 281]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.91      0.77      0.83       855
           1       0.59      0.81      0.68       347

    accuracy                           0.78      1202
   macro avg       0.75      0.79      0.76      1202
weighted avg       0.82      0.78      0.79      1202

AUC-ROC Score: 0.8708



In [44]:
# Decision Tree
decision_tree = DecisionTreeClassifier(class_weight='balanced', random_state=42)
decision_tree.fit(X_train_scaled,y_train)

evaluate_and_store("Decision Tree",decision_tree, X_test_scaled, y_test)

=========== Decision Tree ===========
Confusion Matrix:
[[735 120]
 [129 218]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.85      0.86      0.86       855
           1       0.64      0.63      0.64       347

    accuracy                           0.79      1202
   macro avg       0.75      0.74      0.75      1202
weighted avg       0.79      0.79      0.79      1202

AUC-ROC Score: 0.7439



In [46]:
# Random Forest 

random_forest = RandomForestClassifier(class_weight='balanced', n_estimators=100,random_state=42)
random_forest.fit(X_train_scaled, y_train)

evaluate_and_store("Random Forest", random_forest, X_test_scaled, y_test)


=========== Random Forest ===========
Confusion Matrix:
[[810  45]
 [142 205]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       855
           1       0.82      0.59      0.69       347

    accuracy                           0.84      1202
   macro avg       0.84      0.77      0.79      1202
weighted avg       0.84      0.84      0.84      1202

AUC-ROC Score: 0.8897



In [48]:
# XGboost 
ratio = y_train.value_counts()[0] / y_train.value_counts()[1]

xgboost_model = XGBClassifier(scale_pos_weight=ratio, random_state=42, eval_metric='logloss')
xgboost_model.fit(X_train_scaled,y_train)

evaluate_and_store("XGBoost", xgboost_model, X_test_scaled,y_test)

=========== XGBoost ===========
Confusion Matrix:
[[757  98]
 [115 232]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.89      0.88       855
           1       0.70      0.67      0.69       347

    accuracy                           0.82      1202
   macro avg       0.79      0.78      0.78      1202
weighted avg       0.82      0.82      0.82      1202

AUC-ROC Score: 0.8789



In [50]:
# Convert the dictionary to a pandas DataFrame
comparison_df = pd.DataFrame(model_performance).T

# Sort the table by Recall and AUC-ROC (since these are our priority metrics for churn)
comparison_df = comparison_df.sort_values(by=['Recall', 'AUC-ROC'], ascending=[False, False])

# Display the final styled table
print("FINAL MODEL COMPARISON:")
display(comparison_df.style.highlight_max(color='lightgreen', axis=0))

FINAL MODEL COMPARISON:


,Accuracy,Recall,F1-Score,AUC-ROC
Logistic Regression (L1/Lasso),0.781198,0.809798,0.681212,0.870890
Logistic Regression,0.781198,0.809798,0.681212,0.870809
Logistic Regression (L2/Ridge),0.781198,0.809798,0.681212,0.870759
XGBoost,0.822795,0.668588,0.685377,0.878929
Decision Tree,0.792845,0.628242,0.636496,0.743946
Random Forest,0.844426,0.590778,0.686767,0.889669


In [51]:
model_performance

{'Logistic Regression': {'Accuracy': 0.781198003327787,
  'Recall': 0.8097982708933718,
  'F1-Score': 0.6812121212121212,
  'AUC-ROC': 0.8708091073023577},
 'Logistic Regression (L1/Lasso)': {'Accuracy': 0.781198003327787,
  'Recall': 0.8097982708933718,
  'F1-Score': 0.6812121212121212,
  'AUC-ROC': 0.8708900011797025},
 'Logistic Regression (L2/Ridge)': {'Accuracy': 0.781198003327787,
  'Recall': 0.8097982708933718,
  'F1-Score': 0.6812121212121212,
  'AUC-ROC': 0.8707585486290172},
 'Decision Tree': {'Accuracy': 0.7928452579034941,
  'Recall': 0.6282420749279539,
  'F1-Score': 0.6364963503649635,
  'AUC-ROC': 0.7439455988674857},
 'Random Forest': {'Accuracy': 0.8444259567387687,
  'Recall': 0.590778097982709,
  'F1-Score': 0.6867671691792295,
  'AUC-ROC': 0.8896691777474425},
 'XGBoost': {'Accuracy': 0.8227953410981698,
  'Recall': 0.6685878962536023,
  'F1-Score': 0.6853766617429837,
  'AUC-ROC': 0.8789288302408278}}

In [52]:
# We select the Simple Logistic Regression as our final model based on its superior Recall
best_model = log_reg_simple

# Note: We already trained it in the previous cell, so we don't strictly need to fit it again, 
# but it's good practice to ensure the 'best_model' variable holds the fully trained state.
best_model.fit(X_train_scaled, y_train)

# Save the winning model to a file 
joblib.dump(best_model, 'best_churn_model.joblib')

print("Winning model (Simple Logistic Regression) has been saved as 'best_churn_model.joblib'!")


Winning model (Simple Logistic Regression) has been saved as 'best_churn_model.joblib'!
